### ISSUE TITLE
Qt5 support planned

### ISSUE THREAD

**Issue by brylie** [Teuniz/EDFbrowser#30]
I am getting build errors on Ubuntu linux. Other packages on my system have dependencies on Qt5, and so have installed conflicting packages.

What are the plans/timeline for Qt5 support?

**Comment by Teuniz** [comment]
1. On al major distro's (Fedora, Opensuse, Mint) you can install the Qt4 and Qt5 development files together and directly from the official repo's without doing anything special.
They renamed qmake to qmake-qt5 and/or qmake-qt4, depending on which distro you use.
So, if you get build errrors, something else is going wrong.

2. EDFbrowser compiles fine here on Opensuse Leap 42.2 with Qt 5.6.1.
However, I don't recommend Qt5 because it's still buggy and not yet ready for production use.
(Despite what they want to make you believe.)
Even worse, I noticed that some distro's modify the Qt libraries in order to enforce some styles and
behaviour. Often this causes unexpected errors and/or strange behaviours. I noticed this myself when
using the Plasma 5 desktop.

**Comment by brylie** [comment]
OK, cool. I couldn't figure out how to specify which version of Qt to use for qmake, and the qmake-qt4 alias didn't seem to work for me.

In the end, I used Wine and the Windows installer.

**Comment by tillea** [comment]
Hi,
Debian will drop Qt4 support with the next release and edfbrowser has received an according [bug report](https://bugs.debian.org/874858)
It would be great if you could upgrade to Qt5 soon.
Kind regards, Andreas.

**Comment by Teuniz** [comment]
Hi Andreas,
EDFbrowser compiles fine with Qt 5.9.1.
Kind Regards,
Teunis

**Comment by Teuniz** [comment]
Closed because the issue has been resolved with version 1.60 (released now).
EDFbrowser will require Qt4 version >= 4.7.1 or Qt5 version >= 5.9.1

**Comment by brylie** [comment]
I tried building on Kubuntu 17.04, and got build errors. In the related issue, I am being instructed to install Qt4.

I believe this issue should be re-opened, and renamed to 'deprecate dependency on Qt4' for clarification.

**Comment by tillea** [comment]
Hi,

On Mon, Sep 18, 2017 at 07:16:44AM +0000, Brylie Christopher Oxley wrote:
> I tried building on Kubuntu 17.04, and got build errors. In the related issue, I am being instructed to install Qt4.

You should probably try the packaging git repository.  It builds fine
for 1.59 as well as the just uploaded 1.60.  No need to install Qt4.

> I believe this issue should be re-opened, and renamed to 'deprecate dependency on Qt4' for clarification.

Not in the Debian BTS where it can be considered fixed.

Kind regards

      Andreas.

-- 
http://fam-tille.de
