### ISSUE TITLE
Feature Request: Open Annotations file via command line and/or drag and drop

### ISSUE THREAD

**Issue by raubsau** [Teuniz/EDFbrowser#35]
Having to work with many single short EDF files, I would like to be able to open an annotations file via a command line argument. Currently. importing annotation files requires many clicks and time-

1. The import settings (CSV vs. XML, line where data starts etc.) are stored and can be taken as a template already.
2. If given an annotations file, the annotations editor should be opened/shown automatically.

(3. Bonus: when exporting annotations, the default file name should be the same as given during the import.)

Is any of that doable?

**Comment by Teuniz** [comment]
Make sure your annotations are stored in EDF+ format, that way you don't need to manually convert or import them. It's completely fine to have an EDF+ file that contains only an annotation channel and
no signals.
These converters are just a workaround in order to deal with other software that haven't yet implemented EDF+.
So, in order to avoid the conversions, the software that produced the annotations need to adopt EDF+. This can be done quickly and easy by using the free EDFlib library. That library uses a very permissive license so that it also can be used in commercial/closed source software.

**Comment by raubsau** [comment]
Dear Teuniz,
thank you for your reply.

Maybe my explanation above was not so clear, so I would like to be more specific:
our ASCII annotations (created and/or edited by several people) are imported into Excel, R and as Pandas Data Frames, and also edited by hand with with a text editor sometimes.

My desired workflow/call would be:
`edfbrowser Recording12345.edf --rae Recording12345_annotations.txt`
with --rae being an option that accepts a given file name.
EDFbrowser would start, open `Recording12345.edf`, import `Recording12345_annotations.txt`, and show the annotatations in the Annotations editor. 
After editing with EDFbrowser, when exporting, the default file name in the prompt is `Recording12345_annotations.txt` (right now it is `Recording12345` no matter the original file name).

Does that make more sense?
Best regards
Raubsau

**Comment by raubsau** [comment]
Thanks, that makes sense. I'll see what I can do.
Best regards
Raubsau
